# Copyright 2021 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
VERSION 0.6


repos-file:
  FROM ubuntu:jammy
  # Disable prompting during package installation
  ARG DEBIAN_FRONTEND=noninteractive
  WORKDIR /root

  # RUN apt-get update && add-apt-repository universe && apt-get update && apt-get install -y software-properties-common
  RUN apt-get update && apt-get install -y curl gnupg lsb-release

  # yq is required to filter out unwanted repos included by rosinstall_generator
  RUN curl -sSL https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_386 \
    -o /usr/bin/yq && \
    chmod +x /usr/bin/yq

  RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
  RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
  RUN apt update && apt-get install -y python3-rosinstall-generator


  COPY excluded-pkgs.txt ./
  COPY spaceros-pkgs.txt ./
  COPY spaceros.repos ./
  COPY scripts/generate-repos.sh ./
  # Install repos file generator script requirements.
  RUN ./generate-repos.sh \
        --packages "$(cat spaceros-pkgs.txt)" \
        --exclude-packages "$(cat excluded-pkgs.txt)" \ # Exclude packages which we don't incorporate into Space ROS
        --exclude-installed "false" \ # no ros packages are installed in base image, so we set it to false
        --outfile ros2.repos

  # yq is required for merging file generated by rosinstall with `spaceros.repos` file
  RUN curl -sSL https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_386 \
    -o /usr/bin/yq && \
    chmod +x /usr/bin/yq


  # merge ros2.repos generated by rosinstall with `spaceros.repos`, sort keys and remove comments from files
  RUN yq -i '. *= load("spaceros.repos") | sort_keys(.repositories) | ... comments=""' ros2.repos 

  SAVE ARTIFACT ros2.repos AS LOCAL ros2.repos
